[build] Suppress -Wunused-but-set-var in acpica
This patch suppresses -Wunused-but-set-variable warning in
acpica third party code that does not comply with.

The code that causes the issue is as the following:
1) third_party/acpica/source/components/namespace/nsaccess.c:341:29:
   error: variable 'NumCarats' set but not used
2) third_party/acpica/source/common/dmtbdump.c:82:29:
   error: parameter 'AbsoluteOffset' set but not used

Bug: 96410
Change-Id: I69b27e67fa47c2d8275ebaadbead2c1a21b6337c